{"name": "User enter info in the fields: 1. First Name, 2.Last Name, 3.Email Address, 4. Phone Number, 5. Message, etc.", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//iframe[@src='https://services.cognitoforms.com/f/FFbINltml0S-xBx3VsN1lg?id=1']\"}\n  (Session info: chrome=79.0.3945.130)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\contact_us_dt_15_feb_2020.py\", line 11, in frst_name_entrd\n    context.app.contact_us_page.frst_nm_entered(f_name)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\tellus_dt_04_feb_2020\\pages\\contact_us_page.py\", line 28, in frst_nm_entered\n    self.driver.switch_to.frame(self.driver.find_element_by_xpath(\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 394, in find_element_by_xpath\n    return self.find_element(by=By.XPATH, value=xpath)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1581982204020, "stop": 1581982219486}, {"name": "Then Click on contact us button", "status": "passed", "start": 1581982219486, "stop": 1581982224606}, {"name": "Then First Name Test_name", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//iframe[@src='https://services.cognitoforms.com/f/FFbINltml0S-xBx3VsN1lg?id=1']\"}\n  (Session info: chrome=79.0.3945.130)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\contact_us_dt_15_feb_2020.py\", line 11, in frst_name_entrd\n    context.app.contact_us_page.frst_nm_entered(f_name)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\tellus_dt_04_feb_2020\\pages\\contact_us_page.py\", line 28, in frst_nm_entered\n    self.driver.switch_to.frame(self.driver.find_element_by_xpath(\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 394, in find_element_by_xpath\n    return self.find_element(by=By.XPATH, value=xpath)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1581982224606, "stop": 1581982232657}, {"name": "Then Last Name Test_last_name", "status": "skipped", "start": 1581982234951, "stop": 1581982234951}, {"name": "Then Email Address TestLogin1234!@gmail.com", "status": "skipped", "start": 1581982234952, "stop": 1581982234952}, {"name": "Then Phone Number 1 407 435 44 33", "status": "skipped", "start": 1581982234952, "stop": 1581982234952}, {"name": "Then Message Test_message", "status": "skipped", "start": 1581982234952, "stop": 1581982234952}, {"name": "Then Click on Sumbit button", "status": "skipped", "start": 1581982234952, "stop": 1581982234952}, {"name": "Then Verify \"Thank you! A representative will be in touch.\" sign is here", "status": "skipped", "start": 1581982234952, "stop": 1581982234952}], "start": 1581982194427, "stop": 1581982234952, "uuid": "2eb94e24-3d38-41fc-8673-0e5d20b551ff", "historyId": "0816776f413123d15725a73872b2e79e", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Contact us form"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}